Traceback (most recent call last):
  File "/home/mkzia/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mkzia/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mkzia/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mkzia/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mkzia/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mkzia/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/mkzia/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mkzia/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sqlite3
import pandas as pd

conn = sqlite3.connect('bakery_sales.db')

sql_statement = """
SELECT 
	PatientGender,
	PatientMaritalStatus, 
	count(*) StatusCount, 
	rank() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusRank,
	row_number() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusRowNumber,
	dense_rank() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusDenseRank
FROM 
PatientCorePopulatedTable
GROUP BY PatientGender, PatientMaritalStatus
"""
df = pd.read_sql_query(sql_statement, conn)
df.style.set_table_attributes('style="font-size: 12px"')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOperationalError[0m                          Traceback (most recent call last)
[0;32m~/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py[0m in [0;36mexecute[0;34m(self, *args, **kwargs)[0m
[1;32m   2055[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2056[0;31m             [0mcur[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2057[0m             [0;32mreturn[0m [0mcur[0m[0;34m[0m[0;34m[0m[0m

[0;31mOperationalError[0m: no such table: PatientCorePopulatedTable

The above exception was the direct cause of the following exception:

[0;31mDatabaseError[0m                             Traceback (most recent call last)
[0;32m/tmp/ipykernel_5050/2112602880.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0mGROUP[0m [0mBY[0m [0mPatientGender[0m[0;34m,[0m [0mPatientMaritalStatus[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m """
[0;32m---> 18[0;31m [0mdf[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_sql_query[0m[0;34m([0m[0msql_statement[0m[0;34m,[0m [0mconn[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0mdf[0m[0;34m.[0m[0mstyle[0m[0;34m.[0m[0mset_table_attributes[0m[0;34m([0m[0;34m'style="font-size: 12px"'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py[0m in [0;36mread_sql_query[0;34m(sql, con, index_col, coerce_float, params, parse_dates, chunksize, dtype)[0m
[1;32m    434[0m     """
[1;32m    435[0m     [0mpandas_sql[0m [0;34m=[0m [0mpandasSQL_builder[0m[0;34m([0m[0mcon[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 436[0;31m     return pandas_sql.read_query(
[0m[1;32m    437[0m         [0msql[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    438[0m         [0mindex_col[0m[0;34m=[0m[0mindex_col[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py[0m in [0;36mread_query[0;34m(self, sql, index_col, coerce_float, params, parse_dates, chunksize, dtype)[0m
[1;32m   2114[0m [0;34m[0m[0m
[1;32m   2115[0m         [0margs[0m [0;34m=[0m [0m_convert_params[0m[0;34m([0m[0msql[0m[0;34m,[0m [0mparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2116[0;31m         [0mcursor[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2117[0m         [0mcolumns[0m [0;34m=[0m [0;34m[[0m[0mcol_desc[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;32mfor[0m [0mcol_desc[0m [0;32min[0m [0mcursor[0m[0;34m.[0m[0mdescription[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   2118[0m [0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py[0m in [0;36mexecute[0;34m(self, *args, **kwargs)[0m
[1;32m   2066[0m [0;34m[0m[0m
[1;32m   2067[0m             [0mex[0m [0;34m=[0m [0mDatabaseError[0m[0;34m([0m[0;34mf"Execution failed on sql '{args[0]}': {exc}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2068[0;31m             [0;32mraise[0m [0mex[0m [0;32mfrom[0m [0mexc[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2069[0m [0;34m[0m[0m
[1;32m   2070[0m     [0;34m@[0m[0mstaticmethod[0m[0;34m[0m[0;34m[0m[0m

[0;31mDatabaseError[0m: Execution failed on sql '
SELECT 
	PatientGender,
	PatientMaritalStatus, 
	count(*) StatusCount, 
	rank() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusRank,
	row_number() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusRowNumber,
	dense_rank() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusDenseRank
FROM 
PatientCorePopulatedTable
GROUP BY PatientGender, PatientMaritalStatus
': no such table: PatientCorePopulatedTable
DatabaseError: Execution failed on sql '
SELECT 
	PatientGender,
	PatientMaritalStatus, 
	count(*) StatusCount, 
	rank() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusRank,
	row_number() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusRowNumber,
	dense_rank() OVER (PARTITION BY PatientGender ORDER BY COUNT(*) DESC) StatusDenseRank
FROM 
PatientCorePopulatedTable
GROUP BY PatientGender, PatientMaritalStatus
': no such table: PatientCorePopulatedTable

